//
//  WCPinYinTable.m
//  HelloNSString
//
//  Auto generated by %{file} on %{timestamp}.
//  !!! Don't modify it manually
//  Copyright © 2020 wesley_chen. All rights reserved.
//

#import "WCPinYinTable.h"

static dispatch_once_t sOnceToken;
static WCPinYinTable *sInstance;
static dispatch_queue_t sQueue;

@interface WCPinYinTable ()
@property (nonatomic, strong, readwrite) NSDictionary<NSNumber *, NSArray<NSString *> *> *unicode2PinYin;
@end

@implementation WCPinYinTable

+ (instancetype)sharedInstance {
    dispatch_once(&sOnceToken, ^{
        if (!sQueue) {
            sQueue = dispatch_queue_create("com.wc.WCPinYinTable", DISPATCH_QUEUE_SERIAL);
        }
        dispatch_sync(sQueue, ^{
            sInstance = [[WCPinYinTable alloc] init];
        });
    });
    
    return sInstance;
}

+ (void)cleanup {
    dispatch_sync(sQueue, ^{
        sInstance = nil;
        sOnceToken = 0;
    });
}

#pragma mark -

- (instancetype)init {
    self = [super init];
    if (self) {
        _unicode2PinYin = %{unicode2PinYin}
    }
    return self;
}

@end
