# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!

target 'ConflictFrameworkName' do
end

target 'FrameworkA' do
  pod 'AFNetworking'
end

target 'FrameworkB' do
  pod 'AFNetworking'
end
