platform :ios, '8.0'

# Note: toggle this line to test
use_frameworks!

target 'HelloXCAssets_Example' do
  pod 'HelloXCAssets', :path => '../'

  target 'HelloXCAssets_Tests' do
    inherit! :search_paths

    
  end
end
