use_frameworks!
platform :ios, '8.0'

target 'HelloCoreDataWithCocoaPods_Example' do
  pod 'HelloCoreDataWithCocoaPods', :path => '../'

  target 'HelloCoreDataWithCocoaPods_Tests' do
    inherit! :search_paths

    
  end
end
