#use_frameworks!

platform :ios, '8.0'

target 'PodspecResourceBundle_Example' do
  pod 'PodspecResourceBundle', :path => '../'

  target 'PodspecResourceBundle_Tests' do
    inherit! :search_paths

    
  end
end
