# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

target 'HelloCocoaPods-DynamicFrameworkIntegration' do
  use_frameworks!
  
  # For production mode
  # pod 'AwesomeSDK', :path => "../AwesomeSDK/AwesomeSDK_production.podspec"
  
  # For development mode
  pod 'AwesomeSDK', :path => "../AwesomeSDK/AwesomeSDK_development.podspec"
end
