# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

target 'HelloCocoaPods-DynamicFrameworkIntegration' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloCocoaPods-DynamicFrameworkIntegration

  pod 'AwesomeSDK', :path => "../AwesomeSDK/AwesomeSDK_production.podspec"
end
