# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ActionExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActionExtension
  pod 'SharedLibrary', :path => 'SharedLibrary/SharedLibrary.podspec'

end

target 'HelloConditionalCompilation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloConditionalCompilation
  pod 'SharedLibrary', :path => 'SharedLibrary/SharedLibrary.podspec'

end
