use_frameworks!

platform :ios, '8.0'

target 'HelloInterfaceImplementationPair_Example' do
  pod 'MyTinySDK', :path => '../'

  target 'HelloInterfaceImplementationPair_Tests' do
    inherit! :search_paths
  end
end
