platform :ios, '9.0'
use_frameworks!

target 'PodspecScriptPhases_Example' do
  pod 'PodspecScriptPhases', :path => '../'

  target 'PodspecScriptPhases_Tests' do
    inherit! :search_paths

    
  end
end
